### ISSUE TITLE
llFindSensor() missing while loop?

### ISSUE THREAD

**Issue by gt7219b** [PulsedLight3D/LIDARLite_StateMachine#4]
In the llFindSensor() code:

The i++ (near the end of the function) increments the i value to try a different address since the register 0x02 does not equal 0x80. But, after i is incremented the function exits. There is no while loop to try the next address. Is this a mistake or am I misunderstanding something? Best regards.

void llFindSensor(){
  uint8_t nackack = 100; // Setup variable to hold ACK/NACK resopnses     
  String myString; // Setup string variable to print outcome
  bool sensorFound = false; // Setup flag to indicate whether a sensor has been found or not
  int i = 0; // Setup a counter
  while (nackack != 0){ // While NACK keep going (i.e. continue polling until sucess message (ACK) is received )
    LIDARLite_ADDRESS = byte(LIDARLite_ADDRESSES[i]); // Set address from addresses array
    nackack = I2c.write(LIDARLite_ADDRESS ,0x41,0x00); // Write 0x00 to read only register 0x41 (will produce an ACK if there is a deice at the device address but won't write anything)
    if(nackack != 0){
      i++; // If no ACK from write, increment to next address
    }else{
      break; // If ACK recieved stop while loop
    }
    delay(2); // Wait 2 ms to prevent overpolling
  }
  byte testValue[1]; // Create array to store bytes from read
  llReadAndWait(0x02,1,testValue); // Read from register 0x02
  if(testValue[0] == 0x80){ // If device at address is LIDAR-Lite, register 0x02 should always equal 0x80
    myString += "Device @ 0x";
    myString += String(byte(LIDARLite_ADDRESS),HEX);  
    myString += " is LIDAR-Lite.";
    smPrintFunctionInit(myString);
  }else{ // If register 0x02 does not equal 0x80, increment to next address and try again
    i++;
  }  
}

**Comment by austinmeyers** [comment]
Thanks for your question, and good catch!... We actually just removed (hacked out) that feature for now b/c we were getting false positives from some other sensors here in the office. Only some prerelease units have that 0x42 address. Unless this is something you need, I will probably just remove that function all together.

**Comment by gt7219b** [comment]
I don't need the functionality. Removing it works for me.

Thanks,

Brad

**Comment by austinmeyers** [comment]
Awesome, I've removed it. Thank you!
